// <auto-generated />
using System;
using KategoriServis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KategoriServis.Migrations
{
    [DbContext(typeof(KategoriDbContext))]
    [Migration("20260813103828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KategoriServis.Domain.Entities.Kategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<Guid?>("UstKategoriId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategoriler", "katalog");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("FiyatGecmis")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkaIsmi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrunAciklamasi")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UrunIsmi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler", "katalog", t =>
                        {
                            t.HasCheckConstraint("CK_Urunler_Fiyat", "\"Fiyat\" >= 0");
                        });
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunGorseli", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GorselSiralamasi")
                        .HasColumnType("integer");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UrunId", "GorselSiralamasi");

                    b.ToTable("UrunGorselleri", "katalog");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunOzelligi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OzellikDegeri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UrunTurId")
                        .HasColumnType("uuid")
                        .HasColumnName("UrunTipiId");

                    b.HasKey("Id");

                    b.HasIndex("UrunTurId", "OzellikAdi");

                    b.ToTable("UrunOzellikleri", "katalog");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunTur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("FiyatFarki")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("integer");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StokKodu")
                        .IsUnique();

                    b.HasIndex("UrunId");

                    b.ToTable("UrunTipleri", "katalog");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.Kategori", b =>
                {
                    b.HasOne("KategoriServis.Domain.Entities.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.Urun", b =>
                {
                    b.HasOne("KategoriServis.Domain.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunGorseli", b =>
                {
                    b.HasOne("KategoriServis.Domain.Entities.Urun", "Urun")
                        .WithMany("Gorseller")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunOzelligi", b =>
                {
                    b.HasOne("KategoriServis.Domain.Entities.UrunTur", "UrunTur")
                        .WithMany("Ozellikler")
                        .HasForeignKey("UrunTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrunTur");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunTur", b =>
                {
                    b.HasOne("KategoriServis.Domain.Entities.Urun", "Urun")
                        .WithMany("UrunTurleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.Urun", b =>
                {
                    b.Navigation("Gorseller");

                    b.Navigation("UrunTurleri");
                });

            modelBuilder.Entity("KategoriServis.Domain.Entities.UrunTur", b =>
                {
                    b.Navigation("Ozellikler");
                });
#pragma warning restore 612, 618
        }
    }
}
