// <auto-generated />
using System;
using KargoServis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KargoServis.Migrations
{
    [DbContext(typeof(KargoDbContext))]
    [Migration("20260813091617_IlkMigrasyon")]
    partial class IlkMigrasyon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KargoServis.Domain.Entities.KargoDurumGecmisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KargoGonderisiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KargoGonderisiId", "OlusturmaTarihi");

                    b.ToTable("KargoDurumGecmisleri", "kargo");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.KargoGonderisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KargoSirketIsmi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SevkiyatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SiparisId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("TahminiTeslimTarihi")
                        .HasColumnType("date");

                    b.Property<string>("TakipNumarasi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TeslimatAdresiAnlikGoruntusu")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SevkiyatId");

                    b.HasIndex("SiparisId");

                    b.HasIndex("TakipNumarasi")
                        .IsUnique()
                        .HasFilter("\"TakipNumarasi\" IS NOT NULL");

                    b.ToTable("KargoGonderileri", "kargo");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.Sevkiyat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SevkiyatTanım")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TakipUrlSablonu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SevkiyatTanım")
                        .IsUnique();

                    b.ToTable("Sevkiyat", "kargo");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.KargoDurumGecmisi", b =>
                {
                    b.HasOne("KargoServis.Domain.Entities.KargoGonderisi", "KargoGonderisi")
                        .WithMany("DurumGecmisi")
                        .HasForeignKey("KargoGonderisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoGonderisi");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.KargoGonderisi", b =>
                {
                    b.HasOne("KargoServis.Domain.Entities.Sevkiyat", "Sevkiyat")
                        .WithMany("Gonderiler")
                        .HasForeignKey("SevkiyatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sevkiyat");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.KargoGonderisi", b =>
                {
                    b.Navigation("DurumGecmisi");
                });

            modelBuilder.Entity("KargoServis.Domain.Entities.Sevkiyat", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
