// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StokServis.Infrastructure.Persistence;

#nullable disable

namespace StokServis.Migrations
{
    [DbContext(typeof(StokDbContext))]
    partial class StokDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StokServis.Domain.Entities.Depo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("DepoAdresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DepoIsmi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sehir")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepoIsmi")
                        .IsUnique();

                    b.ToTable("Depolar", "stok");
                });

            modelBuilder.Entity("StokServis.Domain.Entities.StokHareketi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReferansId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StokKalemiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferansId");

                    b.HasIndex("StokKalemiId", "OlusturmaTarihi");

                    b.ToTable("StokHareketleri", "stok", t =>
                        {
                            t.HasCheckConstraint("CK_StokHareketleri_Miktar", "\"Miktar\" > 0");
                        });
                });

            modelBuilder.Entity("StokServis.Domain.Entities.StokUrunleri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepoKonumu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RezerveMiktar")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<int>("StokUrunMiktar")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<Guid>("UrunTurId")
                        .HasColumnType("uuid")
                        .HasColumnName("UrunTipiId");

                    b.Property<int?>("YenidenSiparisSeviyesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("UrunTurId");

                    b.HasIndex("UrunTurId", "DepoId")
                        .IsUnique();

                    b.ToTable("StokKalemleri", "stok", t =>
                        {
                            t.HasCheckConstraint("CK_StokKalemleri_Miktar", "\"StokUrunMiktar\" >= 0");

                            t.HasCheckConstraint("CK_StokKalemleri_RezerveMiktar", "\"RezerveMiktar\" >= 0 AND \"RezerveMiktar\" <= \"StokUrunMiktar\"");
                        });
                });

            modelBuilder.Entity("StokServis.Domain.Entities.StokHareketi", b =>
                {
                    b.HasOne("StokServis.Domain.Entities.StokUrunleri", "StokUrunleri")
                        .WithMany("Hareketler")
                        .HasForeignKey("StokKalemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StokUrunleri");
                });

            modelBuilder.Entity("StokServis.Domain.Entities.StokUrunleri", b =>
                {
                    b.HasOne("StokServis.Domain.Entities.Depo", "Depo")
                        .WithMany("StokKalemleri")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depo");
                });

            modelBuilder.Entity("StokServis.Domain.Entities.Depo", b =>
                {
                    b.Navigation("StokKalemleri");
                });

            modelBuilder.Entity("StokServis.Domain.Entities.StokUrunleri", b =>
                {
                    b.Navigation("Hareketler");
                });
#pragma warning restore 612, 618
        }
    }
}
